-- Historial de gestiones por visita de showroom

CREATE TABLE IF NOT EXISTS public.showroom_visit_gestiones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_id bigint NOT NULL REFERENCES public.showroom_visits(id) ON DELETE CASCADE,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  type text NOT NULL DEFAULT 'nota',
  content text NOT NULL,
  result text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_showroom_visit_gestiones_visit_id
  ON public.showroom_visit_gestiones(visit_id);

CREATE INDEX IF NOT EXISTS idx_showroom_visit_gestiones_visit_created
  ON public.showroom_visit_gestiones(visit_id, created_at DESC);

ALTER TABLE public.showroom_visit_gestiones ENABLE ROW LEVEL SECURITY;

-- Lectura: admin o asesor de la visita
CREATE POLICY showroom_gestiones_select ON public.showroom_visit_gestiones
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.showroom_visits v
      JOIN public.profiles p ON p.id = auth.uid()
      WHERE v.id = showroom_visit_gestiones.visit_id
        AND (p.role = 'admin' OR v.salesperson_id = auth.uid())
    )
  );

-- Inserción: admin o asesor de la visita; autor = usuario actual
CREATE POLICY showroom_gestiones_insert ON public.showroom_visit_gestiones
  FOR INSERT TO authenticated
  WITH CHECK (
    author_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.showroom_visits v
      JOIN public.profiles p ON p.id = auth.uid()
      WHERE v.id = visit_id
        AND (p.role = 'admin' OR v.salesperson_id = auth.uid())
    )
  );
